# zsh configuration

# Setup history
HISTFILE=~/.zsh_history
HISTSIZE=100000
SAVEHIST=100000

# Addition of the history file
setopt APPEND_HISTORY
 
# Ignore all repetitions of commands
setopt HIST_IGNORE_ALL_DUPS

# Do not display the string found earlier
setopt HIST_FIND_NO_DUPS

# Ignore rows if they are duplicates
setopt HIST_IGNORE_DUPS
 
# Delete empty lines from history file
setopt HIST_REDUCE_BLANKS

# Ignore a record starting with a space
setopt HIST_IGNORE_SPACE

# Do not add history and fc commands to the history
setopt HIST_NO_STORE

# Enabled skim fuzzy finder
source /usr/share/skim/completion.zsh
source /usr/share/skim/key-bindings.zsh

# Source aliases
source $HOME/.aliases

# Add binaries installed via cargo to the path
export PATH="/home/$USER/.cargo/bin:$PATH"

# Start the starship prompt
# Can be updated via `cargo install starship --force`
eval "$(starship init zsh)"
